version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - staticcheck
    - errcheck
    - revive
    - misspell
    - gocritic
    - exhaustive
    - ineffassign
    - prealloc
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    revive:
      rules:
        - name: exported
          severity: warning
